on:
  workflow_dispatch:

jobs:
  publish:

    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
      contents: read   # required for private repo

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Pack (release)
      run: |

        # NOTE: .csproj has reference to 'built' .dll file but it has condition parameter to
        #       avoid file missing error on first build. so, need to build assembly and then
        #       delete resulting, incomplete .nupkg file. then, build again by `dotnet pack` to
        #       create valid package file.
        cd src
        dotnet build  -c Release -p:ContinuousIntegrationBuild=true
        rm -f bin/Release/*.nupkg
        dotnet pack   -c Release -p:ContinuousIntegrationBuild=true

    - name: Test (release)
      run: |
        for FILE in tests/**/Test*.csproj; do
          if [ -f "$FILE" ]; then
            echo "Testing: $FILE"
            dotnet run --project "$FILE"  -c Release -p:ContinuousIntegrationBuild=true
          fi
        done

    ################################
    #  NUGET
    - name: Trusted Publishing (id-token permission required)
      uses: NuGet/login@v1
      id: login  # --> ${{ steps.login.outputs.NUGET_API_KEY }}
      with:
        user: ${{ secrets.NUGET_LOGIN }}

    - name: NuGet Publish
      run: |
        cd src
        dotnet nuget push "bin/Release/*.nupkg"  \
          -k ${{ steps.login.outputs.NUGET_API_KEY }}  \
          -s https://api.nuget.org/v3/index.json \
          --timeout 60
